#!/usr/bin/env ruby
require 'rubygems'
require 'bundler'
Bundler.require(:default)

fqdn = ARGV[0]
domain = Whois7::Domain.new(fqdn)

if domain.available?
  puts "#{fqdn} is AVAILABLE for registration"
else
  puts "#{fqdn} is NOT available for registration"
end
